import globals.Globals

ROASTER_RECIPES = recipemap('roaster_recipes')
BLAST_RECIPES = recipemap('electric_blast_furnace')
CRYSTALLIZATION_RECIPES = recipemap('crystallization_recipes')
EXTRACTOR_RECIPES = recipemap('extractor')
CHEMICAL_BATH_RECIPES = recipemap('chemical_bath')
MIXER_RECIPES = recipemap('mixer')
CENTRIFUGE_RECIPES = recipemap('centrifuge')
VACUUM_RECIPES = recipemap('vacuum_freezer')

   //  GTRecipeHandler.removeRecipesByInputs(ELECTROLYZER_RECIPES,
       //         new ItemStack[] {
    //              OreDictUnifier.get(dust, Phosphorus, 5) })

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustPhosphate')* 5)
                .outputs(metaitem('dustPhosphorus'))
                .fluidOutputs(fluid('steam')*4000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustPhosphate')* 5)
                .outputs(metaitem('dustPhosphorus'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

      //  GTRecipeHandler.removeRecipesByInputs(ELECTROLYZER_RECIPES,
     //    new ItemStack[] {
             //           OreDictUnifier.get(dust, ManganeseSulfate, 6) })

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustManganeseSulfate')* 3)
                .fluidOutputs(fluid('sulfur_dioxide') *2000)
                .outputs(metaitem('dustManganese')* 1)
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        //GTRecipeHandler.removeRecipesByInputs(ELECTROLYZER_RECIPES,
       ///         new ItemStack[] {
                //        OreDictUnifier.get(dust, IronSulfate, 6) })

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustIronSulfate')* 6)
                .fluidOutputs(fluid('sulfur_trioxide')*5000)
                .outputs(metaitem('dustIron'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustErbiumOxide')* 2)
                .outputs(metaitem('dustErbium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustErbiumOxide')*2)
                .outputs(metaitem('dustErbium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustYttriumOxide')*2)
                .outputs(metaitem('dustYttrium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustYttriumOxide')*2)
                .outputs(metaitem('dustYttrium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustScandiumOxide')*2)
                .outputs(metaitem('dustScandium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustScandiumOxide')*2)
                .outputs(metaitem('dustScandium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustDysprosiumOxide')*2)
                .outputs(metaitem('dustDysprosium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustDysprosiumOxide')*2)
                .outputs(metaitem('dustDysprosium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustLanthanumOxide')*2)
                .outputs(metaitem('dustLanthanum'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustLanthanumOxide')*2)
                .outputs(metaitem('dustLanthanum'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustNeodymiumOxide')*2)
                .outputs(metaitem('dustNeodymium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustNeodymiumOxide')*2)
                .outputs(metaitem('dustNeodymium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustCeriumOxide')*2)
                .outputs(metaitem('dustCerium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustCeriumOxide')*2)
                .outputs(metaitem('dustCerium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustHafniumOxide')*2)
                .outputs(metaitem('dustHafnium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustHafniumOxide')*2)
                .outputs(metaitem('dustHafnium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustGadoliniumOxide')*2)
                .outputs(metaitem('dustGadolinium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustGadoliniumOxide')*2)
                .outputs(metaitem('dustGadolinium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(9)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustRutherfordiumOxide')*2)
                .outputs(metaitem('dustRutherfordium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(8)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustRutherfordiumOxide')*2)
                .outputs(metaitem('dustRutherfordium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(8)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustZirconiumOxide')*2)
                .outputs(metaitem('dustZirconium'))
                .fluidOutputs(fluid('steam')*1000)
                .circuitMeta(1)
                .duration(200)
                .EUt(8)
                .buildAndRegister()

        ROASTER_RECIPES.recipeBuilder()
                .inputs(metaitem('dustZirconiumOxide')*2)
                .outputs(metaitem('dustZirconium'))
                .circuitMeta(0)
                .duration(200)
                .EUt(8)
                .buildAndRegister()


// Yttrium Dust * 2
mods.gregtech.electrolyzer.removeByInput(30, [metaitem('dustYttriumOxide') * 5], null)